Revert "sm8350-common: Use armv8-2a for 2nd arch variant"
error: Incorrect TARGET_2ND_ARCH_VARIANT, armv8-2a. Use armv8-a instead

This reverts commit 2c3941f12cea49a42eb23132c52f6fb1e1956ea1.